import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./provider";
import Bottomnav from "@/components/ui/Homecomponets/Bottomnav";
import Header from "@/components/ui/Homecomponets/Header";
import FoodCategories from "@/components/ui/Homecomponets/Categories";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Resto QR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <Header/>
      <FoodCategories/>
        {children}
        <Bottomnav/>
        </Providers>
      </body>
    </html>
  );
}
